modLoader="javafml"
loaderVersion="[31,)"

license="BSD-3-Clause"

[[mods]]
modId="voidbucket"
version="${file.jarVersion}"
displayName="Void Bucket"

# We will come back later.
credits=""

authors=["jihuayu"]

description="Void Bucket."

[[dependencies.nickname]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16, 1.16.4]"
    ordering="NONE"
    side="BOTH"